### ISSUE TITLE
访问链接加密

### ISSUE THREAD

**Issue by EvanderYang** [ACG-Q/BPB-Worker-Panel-CryptDistro#1]
可以修改访问地址吗？
在url/panel 中增加uuid，避免网址扫描。
比如 https://test.pages.dev/23c25e9f-991c-4def-be08-6a6ca43d651e/panel

**Comment by ACG-Q** [comment]
代码源自于 [BPB-Worker-Panel](https://github.com/bia-pain-bache/BPB-Worker-Panel)
我并非开发者，我只是搭建了一个自动化的编译分发系统
